version: '3.9'
services:
  postgres:
    image: postgres:14-alpine
    container_name: loop-datastore 
    restart: always
    ports:
      - '5432:5432'
    env_file:
      - .env
    volumes:
      - loop-datastore_db:/var/lib/postgresql/data

volumes:
  loop-datastore_db:
